name: Merge DEV into prod

on:
  push:
    branches:
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test changes
      run: |
        echo "Running tests"
        # Run tests here

    - name: Merge dev into prod
      if: success()
      run: |
        git checkout PROD
        git merge DEV
        git push origin PROD
      
